export const GET_LIST_CINEMA = 'GET_LIST_CINEMA';
export const GET_LIST_SHOWTIME_BY_CINEMA = 'GET_LIST_SHOWTIME_BY_CINEMA';
export const GET_LIST_CINEMA_BRAND = 'GET_LIST_CINEMA_BRAND';
export const GET_LIST_SEAT = 'GET_LIST_SEAT';
