export const SHOW_LOADING_HOME_TIME = 'SHOW_LOADING_HOME_TIME';
export const HIDE_LOADING_HOME_TIME = 'HIDE_LOADING_HOME_TIME';
export const SHOW_LOADING_THEME = 'SHOW_LOADING_THEME';
export const HIDE_LOADING_THEME = 'HIDE_LOADING_THEME';
export const SHOW_LOADING_SHOW_TIME = 'SHOW_LOADING_SHOW_TIME';
export const HIDE_LOADING_SHOW_TIME = 'HIDE_LOADING_SHOW_TIME';